'use client'

import { useState } from 'react'
import { AI_RECOMMENDATIONS_SEED } from '@/lib/data'
import { PlatformBadge } from '@/components/platform-badge'
import {
  Bell, Lightbulb, RefreshCw, Clock, Hash, Check, X, PlusSquare,
  Sparkles,
} from 'lucide-react'

type Rec = typeof AI_RECOMMENDATIONS_SEED[number]
type Priority = 'high' | 'med' | 'low'
type RecType = 'competitor_alert' | 'post_idea' | 'format_shift' | 'timing' | 'hashtag'

function priorityLabel(p: Priority) {
  if (p === 'high') return { label: 'HIGH', bg: 'bg-[#fc3467]/10', text: 'text-[#fc3467]', border: 'border-[#fc3467]/20' }
  if (p === 'med') return { label: 'MED', bg: 'bg-[#fad74f]/10', text: 'text-[#fad74f]', border: 'border-[#fad74f]/20' }
  return { label: 'LOW', bg: 'bg-[#1e2433]', text: 'text-gray-400', border: 'border-[#1e2433]' }
}

function typeIcon(t: RecType) {
  switch (t) {
    case 'competitor_alert': return Bell
    case 'post_idea': return Lightbulb
    case 'format_shift': return RefreshCw
    case 'timing': return Clock
    case 'hashtag': return Hash
  }
}

function sortPriority(a: Rec, b: Rec) {
  const order: Record<string, number> = { high: 0, med: 1, low: 2 }
  return order[a.priority] - order[b.priority]
}

export default function RecommendationsPage() {
  const [dismissed, setDismissed] = useState<Set<number>>(new Set())
  const [done, setDone] = useState<Set<number>>(new Set())

  const sorted = [...AI_RECOMMENDATIONS_SEED].sort(sortPriority)
  const visible = sorted.filter((_, i) => !dismissed.has(i) && !done.has(i))

  const highCount = AI_RECOMMENDATIONS_SEED.filter(r => r.priority === 'high').length
  const medCount = AI_RECOMMENDATIONS_SEED.filter(r => r.priority === 'med').length
  const lowCount = AI_RECOMMENDATIONS_SEED.filter(r => r.priority === 'low').length

  return (
    <div className="p-6 space-y-6 max-w-[900px]">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">AI Recommendations</h1>
          <p className="text-sm text-gray-500 mt-0.5">Generated by Claude · May 27, 2026</p>
        </div>
        <div className="relative group">
          <button
            disabled
            className="flex items-center gap-2 px-3 py-2 bg-[#0d1117] border border-[#1e2433] rounded-lg text-xs text-gray-600 cursor-not-allowed"
          >
            <Sparkles size={13} />
            Regenerate with AI
          </button>
          <div className="absolute right-0 top-full mt-2 w-56 bg-[#161b22] border border-[#1e2433] rounded-lg p-3 text-xs text-gray-400 hidden group-hover:block shadow-xl z-10">
            Connect an Anthropic API key in Settings to enable live AI recommendation generation.
          </div>
        </div>
      </div>

      {/* Summary strip */}
      <div className="flex items-center gap-4 bg-[#0d1117] border border-[#1e2433] rounded-xl px-4 py-3">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#fc3467]" />
          <span className="text-sm font-semibold text-white">{highCount} High Priority</span>
        </div>
        <span className="text-[#1e2433]">·</span>
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#fad74f]" />
          <span className="text-sm text-gray-400">{medCount} Medium</span>
        </div>
        <span className="text-[#1e2433]">·</span>
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-gray-600" />
          <span className="text-sm text-gray-400">{lowCount} Low</span>
        </div>
        <span className="text-[#1e2433]">·</span>
        <span className="text-sm text-gray-500">Last generated: today</span>
        {(dismissed.size + done.size) > 0 && (
          <>
            <span className="text-[#1e2433]">·</span>
            <span className="text-sm text-gray-500">{done.size} done · {dismissed.size} dismissed</span>
          </>
        )}
      </div>

      {/* Rec Cards */}
      <div className="space-y-3">
        {visible.length === 0 && (
          <div className="bg-[#0d1117] border border-[#1e2433] rounded-xl p-8 text-center">
            <Check size={24} className="text-[#62d070] mx-auto mb-3" />
            <p className="text-white font-semibold">All caught up!</p>
            <p className="text-sm text-gray-500 mt-1">You've actioned all recommendations. Regenerate to get fresh insights.</p>
          </div>
        )}
        {visible.map((rec, originalIdx) => {
          const globalIdx = sorted.indexOf(rec)
          const pStyle = priorityLabel(rec.priority as Priority)
          const Icon = typeIcon(rec.type as RecType)

          return (
            <div
              key={globalIdx}
              className="bg-[#0d1117] border border-[#1e2433] rounded-xl p-5 hover:border-[#2a3447] transition-colors"
            >
              <div className="flex items-start gap-3">
                {/* Icon */}
                <div className="w-8 h-8 rounded-lg bg-[#161b22] flex items-center justify-center shrink-0 mt-0.5">
                  <Icon size={14} className="text-[#75c7e6]" />
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap mb-2">
                    <span className={`px-2 py-0.5 rounded border text-xs font-bold ${pStyle.bg} ${pStyle.text} ${pStyle.border}`}>
                      {pStyle.label}
                    </span>
                    <PlatformBadge platform={rec.platform as 'tiktok' | 'instagram'} />
                    <span className="text-xs text-gray-600 capitalize">{rec.type.replace('_', ' ')}</span>
                  </div>
                  <h3 className="text-sm font-bold text-white mb-1.5 leading-snug">{rec.title}</h3>
                  <p className="text-xs text-gray-400 leading-relaxed">{rec.body}</p>

                  {/* Actions */}
                  <div className="flex items-center gap-2 mt-4">
                    <button
                      onClick={() => setDone(prev => new Set([...prev, globalIdx]))}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-[#62d070]/10 border border-[#62d070]/20 text-[#62d070] rounded-lg text-xs font-medium hover:bg-[#62d070]/20 transition-colors"
                    >
                      <Check size={11} />
                      Mark Done
                    </button>
                    <button
                      onClick={() => setDismissed(prev => new Set([...prev, globalIdx]))}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-[#1e2433] text-gray-400 rounded-lg text-xs font-medium hover:text-white hover:bg-[#2a3447] transition-colors"
                    >
                      <X size={11} />
                      Dismiss
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 bg-[#75c7e6]/10 border border-[#75c7e6]/20 text-[#75c7e6] rounded-lg text-xs font-medium hover:bg-[#75c7e6]/20 transition-colors ml-auto">
                      <PlusSquare size={11} />
                      Create Post
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
